server:
  port: 8080
spring:
  application:
    name:  order_service
  config:
    import:
  datasource:
    url:
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    datasource_platform:
    hibernate:
      ddl-auto: update
      show-sql: true

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
